version: '3.5'
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: .
    ports:
    - 80:8080
  

#  sut:
#    image: alpine:3.13
#    depends_on:
#      - app
#    command: /tmp/run_tests.sh
#    volumes:
#      - "./run_tests.sh:/tmp/run_tests.sh:ro"
