version: '3.5'

services:
  db:
    container_name: ${MY_NAME}_db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nginx_net
    volumes:
      - ${BIND_DIR}/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"      

  periodic-backup:
    ## this sections uses work from https://github.com/ricardolsmendes/docker-samples/
    container_name: ${MY_NAME}_database-backup
    build: ./periodic_backup
    environment:
      MYSQL_CONTAINER_NAME: ${MY_NAME}_db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_KEEP_BACKUP_DAYS: ${MYSQL_KEEP_BACKUP_DAYS}
    networks:
      - nginx_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BIND_DIR}/backup:/backup
    command: crond -f -d 8
    restart: always

  web:
    container_name: ${MY_NAME}_nginx_php-fpm  
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: .
    restart: always
    ports:
      - ${WEB_PORT}:8080
    networks:
      - nginx_net
    depends_on:
      - "db"
    volumes:
      - ${BIND_DIR}/var/www:/var/www

  adminer:
    container_name: ${MY_NAME}_adminer
    image: adminer
    restart: always
    environment: 
      ADMINER_DESIGN: mvt
      # enabling the next line is less secure
      #ADMINER_DEFAULT_SERVER: ${MY_NAME}_db
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - nginx_net
    depends_on:
      - "db"
      
  grafana:
    image: grafana/grafana-enterprise
    container_name: ${MY_NAME}_grafana
    user: "$UID:$GID"
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://localhost/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - ${GRAFANA_PORT}:3000
    networks:
      - nginx_net
    volumes:
      - ${BIND_DIR}/var/lib/grafana:/var/lib/grafana
    depends_on:
      - "db"

networks:
  nginx_net:
    driver: bridge
#  sut:
#    image: alpine:3.13
#    depends_on:
#      - app
#    command: /tmp/run_tests.sh
#    volumes:
#      - "./run_tests.sh:/tmp/run_tests.sh:ro"
