version: '3.5'

services:
  db:
    container_name: ${MY_NAME}_db
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - nginx_net
    volumes:
      - ${BIND_DIR}/mariadb/var/lib/mysql:/var/lib/mysql
      - ${BIND_DIR}/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d
      - ${BIND_DIR}/sql-initdb.d:/docker-entrypoint-initdb.d/:ro
    ports:
      - "127.0.0.1:${MARIADB_PORT}:3306"
    restart: always  

  periodic-backup:
    ## this sections uses work from https://github.com/ricardolsmendes/docker-samples/
    container_name: ${MY_NAME}_database-backup
    build: 
      context: ./periodic_backup
      args: 
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    environment:
      MARIADB_CONTAINER_NAME: ${MY_NAME}_db
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_KEEP_BACKUP_DAYS: ${MARIADB_KEEP_BACKUP_DAYS}
    networks:
      - nginx_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BIND_DIR}/backup:/backup
    command: crond -f -d 8
    restart: always

  web:
    container_name: ${MY_NAME}_nginx_php-fpm
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: 
      context: .
      args: 
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - ${WEB_PORT}:8080
    networks:
      - nginx_net
    depends_on:
      - "db"
    volumes:
      - ${BIND_DIR}/var/www:/var/www
      - ${BIND_DIR}/var/log/nginx:/var/log/nginx
      - ${BIND_DIR}/backup:/backup

  adminer:
    container_name: ${MY_NAME}_adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: mvt
      # enabling the next line is less secure
      #ADMINER_DEFAULT_SERVER: ${MY_NAME}_db
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - nginx_net
    depends_on:
      - "db"

#  set_once:
#    container_name: ${MY_NAME}_set-once
#    build: ./settings
#    restart: unless-stopped
#    volumes:
#      - nginx-config:/etc/nginx
#      - php-config:/etc/php83

  grafana:
    image: grafana/grafana-enterprise
    container_name: ${MY_NAME}_grafana
    user: "$UID:$GID"
    restart: always
    environment:
     - HTTP_PROXY=${HTTP_PROXY}
     - HTTPS_PROXY=${HTTPS_PROXY}
     - GF_SERVER_ROOT_URL=http://localhost/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
     - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
     - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING}
    ports:
     - ${GRAFANA_PORT}:3000
    networks:
      - nginx_net
    volumes:
      - ${BIND_DIR}/grafana/var/lib/grafana:/var/lib/grafana
    depends_on:
      - "db"

networks:
  nginx_net:
    name: nginx_net
    external: true
#  nginx_net:
#    driver: bridge

#sut:
#    image: alpine:3.13
#    depends_on:
#      - app
#    command: /tmp/run_tests.sh
#    volumes:
#      - "./run_tests.sh:/tmp/run_tests.sh:ro"
